# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lazyccg
    main: ./cmd/lazyccg
    binary: lazyccg
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: lazyccg
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

brews:
  - repository:
      owner: atani
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/atani/lazyccg"
    description: "TUI dashboard for monitoring Claude Code / Codex / Gemini sessions in kitty terminal"
    license: "MIT"
    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
    install: |
      bin.install "lazyccg"
    test: |
      assert_match "poll interval", shell_output("#{bin}/lazyccg -h 2>&1", 2)
